on:
  push:
  pull_request:

name: Test & Build Release
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - name: Test
        run: sudo go test -v -coverprofile='coverage.out' -covermode=count ./...

  Build:
    needs: test
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v2
        with:
          go-version: "1.18"

      - run: bash .cross_compile.sh

      - name: Release
        uses: softprops/action-gh-release@v1
        with: # å°†ä¸‹è¿°å¯æ‰§è¡Œæ–‡ä»¶ release ä¸ŠåŽ»
          draft: false # Releaseè‰ç¨¿
          files: |
            dist/nexttrace_darwin_amd64
            dist/nexttrace_darwin_arm64
            dist/nexttrace_linux_386
            dist/nexttrace_linux_amd64
            dist/nexttrace_linux_arm64
            dist/nexttrace_linux_armv7
            dist/nexttrace_linux_mips
            dist/nexttrace_openbsd_amd64
            dist/nexttrace_openbsd_arm64
            dist/nexttrace_freebsd_amd64
            dist/nexttrace_freebsd_arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GT_Token }}
  publish-new-formula:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: config git
        run: |
          git config --global user.email "${{ secrets.git_mail }}"
          git config --global user.name "${{ secrets.git_name }}"
      - name: Clone repo
        run: |
          git clone https://github.com/xgadget-lab/homebrew-nexttrace.git
      - name: Exec scipt
        run: |
          cd homebrew-nexttrace
          bash genFormula.sh
      # - name: setup SSH keys and known_hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      #     ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #     ssh-add - <<< "${{ secrets.ID_RSA }}"
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - name: Git Push
        run: |
          cd homebrew-nexttrace
          git commit -am 'Publish a new version with Formula'
          git remote set-url origin https://${{ secrets.gt_token }}@github.com/xgadget-lab/homebrew-nexttrace.git
          git push
        # env:
        #   SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - run: echo "ðŸ This job's status is ${{ job.status }}."