name: Publish New Formula

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  publish-new-formula:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a single command using the runners shell
      - name: config git
        run: |
          git config --global user.email "${{ secrets.git_mail }}"
          git config --global user.name "${{ secrets.git_name }}"
      - name: Clone repo
        run: |
          git clone https://github.com/nxtrace/homebrew-nexttrace.git
      - name: Exec scipt
        run: |
          cd homebrew-nexttrace
          bash genFormula.sh
      # - name: setup SSH keys and known_hosts
      #   run: |
      #     mkdir -p ~/.ssh
      #     ssh-keyscan github.com >> ~/.ssh/known_hosts
      #     ssh-agent -a $SSH_AUTH_SOCK > /dev/null
      #     ssh-add - <<< "${{ secrets.ID_RSA }}"
      #   env:
      #     SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - name: Git Push
        run: |
          cd homebrew-nexttrace
          git commit -am 'Publish a new version with Formula' || true
          git remote set-url origin https://${{ secrets.gt_token }}@github.com/nxtrace/homebrew-nexttrace.git
          git push
        # env:
        #   SSH_AUTH_SOCK: /tmp/ssh_agent.sock
      - run: echo "ðŸ This job's status is ${{ job.status }}."
